apiVersion: v1
kind: Service
metadata:
  name: base-site-svc
  namespace: secapp
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    environnement: prod

