apiVersion: v1
kind: Service
metadata:
  name: base-server-svc
  namespace: secapp
spec:
  type: ClusterIP
  ports:
  - port: 8444
    targetPort: 8443
    protocol: TCP
  selector:
    environnement: prod
